server.port: 8080

solon.app:
  name: 'demo-app'
  group: 'demo'

solon.logging:
  appender:
    file:
      enable: false
  logger:
    root:
      level: DEBUG

# for dubbo
dubbo:
  application:
    name: ${solon.app.name}
    logger: slf4j
  registry:
    address: N/A
  consumer:
    scope: local
